apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mini-platform-ingress
spec:
  rules:
    - host: mini.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mini-platform-service
                port:
                  number: 80